[catppuccin-for-vscode]
[catppuccin-icons]
[clangd]
[cmake-tools]
[code-lldb]
[dev-containers]
[docker]
[error-lens]
[even-better-toml]
[git-lens]
[go]
[indent-rainbow]
[javascript-and-typescript]
[json5-syntax]
[latex-workshop]
[lean4]
[makefile-tools]
[markdown-all-in-one]
[markdown-table-formatter]
[prettier]
[pylance]
[python]
[python-debugger]
[remote-ssh]
[remote-tunnels]
[remote-development]
[remote-explorer]
[remote-ssh-editing-configuration-files]
[rust-analyzer]
[sql-tools]
[sql-tools-mysql-mariadb-tidb]
[thunder-client]
[todo-tree]
[vim]
[vacode-proto3]