[enable]
clang = true
lua = true
rust = true
python = true
go = false
latex = true

[config]
clang = 'clangd'
lua = 'lua_ls'
rust = 'rust_analyzer'
python = 'pylsp'
go = 'gopls'
latex = 'texlab'

[pkg]
clang = 'clangd'
lua = 'lua-language-server'
rust = 'rust-analyzer'
python = 'python-lsp-server'
go = 'gopls'
latex = 'texlab'


